---
title: "Datasaurus"
author: "James P. Hare"
date: "10/13/2020"
output: github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(broom)
library(gridExtra)

theme_set(theme_void())

datasaurus <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-10-13/datasaurus.csv')
```

```{r}
glimpse(datasaurus)
summary(datasaurus)
```

```{r}
datasaurus %>%
        group_by(dataset) %>% 
        summarize(Mean_X = mean(x),
                  Mean_Y = mean(y),
                  SD_X = sd(x),
                  SD_Y = sd(y),
                  Corr = cor(x, y)
                  )
        
```

```{r}
datasaurus %>%
        nest(data = -dataset) %>% 
        mutate(model = map(data, ~ lm(y ~ x, data = .)),
               tidied = map(model, tidy)
        ) %>% 
        unnest(tidied) %>% 
        select(-data, -model)
```

```{r}
datasaurus %>% 
        ggplot(aes(x, y, color = dataset)) +
        geom_point() +
        geom_smooth(method = "lm", formula = y ~ x) +
        theme(legend.position = 0)
```


```{r}
dino <- datasaurus %>%
        filter(dataset == "dino") %>%
        ggplot(aes(x, y)) +
        geom_point() +
        theme(legend.position = "none") +
        labs(title = "Each of These Plots Has Nearly Identical Summary Statistics",
             subtitle = "Visualization is an essential component of data exploration",
             caption = "")


dozen <- datasaurus %>%
        filter(dataset != "dino") %>%
        ggplot(aes(x, y, color = dataset)) +
        geom_point() +
        facet_wrap( ~ dataset) +
        theme(legend.position = "none",
              strip.text = element_blank())+
        labs(title = "",
             subtitle = "",
             caption = "Simulated Data: Alberto Cairo")


grid.arrange(dino, dozen, ncol = 2)
```

