---
title: "US Spending on Kids"
author: "James P. Hare"
date: "9/14/2020"
output: github_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tilemaps)
library(sf)

kids <-
  readr::read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-15/kids.csv',
    col_types = cols(
      state = col_character(),
      variable = col_character(),
      year = col_factor(),
      raw = col_double(),
      inf_adj = col_double(),
      inf_adj_perchild = col_double()
    )
  )
```

```{r wrangle}
PK12_spending <- kids %>%
  filter(variable == "PK12ed") %>%
  group_by(state) %>%
  mutate(percent_change = (((inf_adj_perchild[year == 2016] /
                               inf_adj_perchild[year == 1997]) - 1
  ) * 100)) %>%
  select(state, percent_change)

#modify code from https://github.com/kaerosen/tilemaps/blob/master/data-raw/governors.R to include DC
#rewrite code to Tidyverse style
states <- spData::us_states[, c("NAME", "geometry")] %>%
  arrange(NAME) %>%
  mutate(
    abbreviation =   c(
      "AL",
      "AZ",
      "AR",
      "CA",
      "CO",
      "CT",
      "DE",
      "DC",
      "FL",
      "GA",
      "ID",
      "IL",
      "IN",
      "IA",
      "KS",
      "KY",
      "LA",
      "ME",
      "MD",
      "MA",
      "MI",
      "MN",
      "MS",
      "MO",
      "MT",
      "NE",
      "NV",
      "NH",
      "NJ",
      "NM",
      "NY",
      "NC",
      "ND",
      "OH",
      "OK",
      "OR",
      "PA",
      "RI",
      "SC",
      "SD",
      "TN",
      "TX",
      "UT",
      "VT",
      "VA",
      "WA",
      "WV",
      "WI",
      "WY"
    )
  ) %>%
  sf::st_transform(3857) %>%
  mutate(tile_map = generate_map(geometry, square = FALSE, flat_topped = TRUE))

states <- states %>%
  add_row(
    NAME = "Alaska",
    abbreviation = "AK",
    tile_map = create_island(states$tile_map, "lower left")
  ) %>%
  add_row(
    NAME = "Hawaii",
    abbreviation = "HI",
    tile_map = create_island(states$tile_map, c(-12050000, 3008338))
  ) %>%
  arrange(NAME)

states <- states %>%
  left_join(PK12_spending, by = c("NAME" = "state"))

remove(kids)
remove(PK12_spending)
```

```{r map}
ggplot(states) +
  geom_sf(aes(geometry = tile_map, fill = percent_change)) +
  geom_sf_text(
    aes(geometry = tile_map, label = abbreviation),
    fun.geometry = function(x)
      st_centroid(x)
  ) +
  labs(title = "Pre-K to 12th Grade Education Spending by State",
       subtitle = "Per child spending in 2016",
       caption = "Source: Urban Institute") +
  scale_fill_viridis_b() +
  theme_void() +
  theme()
```


